### ISSUE TITLE
add option to build installer from git ref

### ISSUE THREAD

**Issue by sallyom** [ironcladlou/openshift4-libvirt-gcp#1]
To use this setup in CI, in update-installer, we'll need the option to build from a git ref rather than installer/master, here: https://github.com/ironcladlou/openshift4-libvirt-gcp/blob/master/tools/update-installer#L11

**Comment by zeenix** [comment]
@sallyom is this still unresolved? I see that branch is configurable.

**Comment by praveenkumar** [comment]
It is already fixed, closing this one.
